const fs=require('fs');const path=require('path');const vm=require('vm');
const root=path.resolve(__dirname,'..');
const memory=new Map();
global.window=global;global.localStorage={getItem:k=>memory.has(k)?memory.get(k):null,setItem:(k,v)=>memory.set(k,String(v)),removeItem:k=>memory.delete(k),clear:()=>memory.clear(),key:i=>[...memory.keys()][i]||null,get length(){return memory.size;}};
global.navigator={onLine:true};global.location={protocol:'http:',hostname:'localhost'};
function load(file){vm.runInThisContext(fs.readFileSync(path.join(root,file),'utf8'),{filename:file});}
['config.js','js/profiles.js','js/visuals.js','js/curriculum.js','js/core.js','js/storage.js','js/engine.js'].forEach(load);
let passed=0;function test(name,fn){try{fn();console.log('PASS',name);passed++;}catch(err){console.error('FAIL',name,'\n ',err.stack||err);process.exitCode=1;}}
function assert(cond,msg='assertion failed'){if(!cond)throw new Error(msg);}function eq(a,b,msg){if(JSON.stringify(a)!==JSON.stringify(b))throw new Error(msg||`${JSON.stringify(a)} !== ${JSON.stringify(b)}`);}

test('curriculum has 184 structured units',()=>assert(FLH_CURRICULUM.units.length===184));
test('locked family assumptions are present',()=>{assert(FLH_PROFILES.arezoo.levels.en==='A1');assert(FLH_PROFILES.arezoo.levels.de==='A1');assert(FLH_PROFILES.elena.age===11);assert(FLH_PROFILES.aria.age===3);});
test('daily plan is deterministic',()=>{FLH_STORE.reset();const a=FLH_ENGINE.buildDailyPlan({force:true}),b=FLH_ENGINE.buildDailyPlan({force:true});eq(a.steps.map(x=>({id:x.id,type:x.type,choices:x.choices,items:x.items?.map(i=>i.id)})),b.steps.map(x=>({id:x.id,type:x.type,choices:x.choices,items:x.items?.map(i=>i.id)})));});
test('same task cannot farm XP',()=>{FLH_STORE.reset();const plan=FLH_ENGINE.buildDailyPlan({force:true}),task=plan.steps[0];FLH_ENGINE.completeTask(task,{score:90,minutes:3,correct:true});const xp1=FLH_STORE.get().progress.saeed.en.xp;FLH_ENGINE.completeTask(task,{score:90,minutes:3,correct:true});const p=FLH_STORE.get().progress.saeed.en;assert(p.xp===xp1,'XP changed on repeat');assert(p.units[task.unitId].attempts===2);});
test('mastery model records stability and review',()=>{const m1=FLH_CORE.updateMastery({}, {score:90,retrieval:90,independence:90},75);const m2=FLH_CORE.updateMastery(m1,{score:92,retrieval:90,independence:90},75);assert(m2.mastery>=75);assert(m2.successfulAttempts===2);assert(m2.nextReviewAt);});
test('incorrect objective answer enters error book',()=>{FLH_STORE.reset();const u=FLH_ENGINE.currentUnit(),task={id:'bad-task',profile:'saeed',targetLanguage:'en',unitId:u.id,unitTitle:u.titleFa,skill:'listening',type:'listen-mcq',answer:'correct',minutes:2};FLH_ENGINE.completeTask(task,{score:35,correct:false,userAnswer:'wrong',correctAnswer:'correct'});assert(FLH_STORE.get().errorBook.some(e=>e.taskId==='bad-task'));});
test('vocabulary cards use spaced repetition',()=>{FLH_STORE.reset();const u=FLH_ENGINE.currentUnit(),task={id:'vocab-task',profile:'saeed',targetLanguage:'en',unitId:u.id,unitTitle:u.titleFa,skill:'vocabulary',type:'flash',items:[{id:'hello',target:'hello',fa:'سلام'}],minutes:2};FLH_ENGINE.completeTask(task,{score:90,correct:true});const card=FLH_STORE.get().vocab[0];assert(card&&card.dueAt);FLH_ENGINE.reviewVocab(card.id,5);const updated=FLH_STORE.get().vocab.find(x=>x.id===card.id);assert(updated.repetitions===1&&updated.interval===1);});
test('unit access is sequential',()=>{FLH_STORE.reset();const ctx=FLH_ENGINE.active(),units=FLH_ENGINE.levelUnits('en','B1','saeed');assert(FLH_ENGINE.unitAccess(units[1],ctx).state==='locked');FLH_STORE.update(s=>{s.progress.saeed.en.units[units[0].id]={mastery:80,mastered:true,attempts:2,averageScore:80};return s;});assert(FLH_ENGINE.unitAccess(units[1],FLH_ENGINE.active()).state==='available');});
test('level readiness requires assessment',()=>{FLH_STORE.reset();const units=FLH_ENGINE.levelUnits('en','B1','saeed');FLH_STORE.update(s=>{const p=s.progress.saeed.en;for(const u of units)p.units[u.id]={mastery:85,mastered:true,attempts:2,averageScore:85};for(const k of Object.keys(p.skills))p.skills[k]=80;return s;});assert(!FLH_ENGINE.levelReadiness('B1').ready);FLH_ENGINE.recordAssessment('B1',{listening:80,speaking:80,reading:80,writing:80});assert(FLH_ENGINE.levelReadiness('B1').ready);});
test('event merge is idempotent and latest-wins',()=>{const a=[{id:'1',createdAt:'2026-01-01T00:00:00Z',v:1}],b=[{id:'1',updatedAt:'2026-01-02T00:00:00Z',v:2},{id:'2',createdAt:'2026-01-01T00:00:00Z'}];const m=FLH_CORE.mergeEvents(a,b);assert(m.length===2);assert(m.find(x=>x.id==='1').v===2);eq(FLH_CORE.mergeEvents(m,m),m);});
test('Arya always receives PRE parent-guided session',()=>{FLH_STORE.reset();FLH_STORE.update(s=>{s.active={...s.active,profile:'aria',language:'de',level:'PRE',duration:7,goal:FLH_PROFILES.aria.goals.de[0]};return s;});const plan=FLH_ENGINE.buildDailyPlan({force:true});assert(plan.level==='PRE');assert(plan.steps.length===6);assert(plan.steps.every(x=>x.profile==='aria'));});


test('active plan persists without duplicate save churn',()=>{FLH_STORE.reset();const plan=FLH_ENGINE.buildDailyPlan({force:true});FLH_STORE.savePlan(plan);const same=FLH_ENGINE.buildDailyPlan();assert(same.id===plan.id);assert(same.engineVersion==='6.1.0-core');});
test('snapshot merge preserves local and remote records',()=>{FLH_STORE.reset();const local=FLH_STORE.get();local.events=[{id:'local',createdAt:'2026-01-01T00:00:00Z'}];const remote=JSON.parse(JSON.stringify(local));remote.events=[{id:'remote',createdAt:'2026-01-02T00:00:00Z'}];remote.progress.saeed.en.units['en-b1-01']={mastery:82,lastAt:'2026-01-02T00:00:00Z'};FLH_STORE.mergeRemoteSnapshot(remote);const merged=FLH_STORE.get();assert(merged.events.some(e=>e.id==='local')&&merged.events.some(e=>e.id==='remote'));assert(merged.progress.saeed.en.units['en-b1-01'].mastery===82);});

if(!process.exitCode)console.log(`\n${passed} core tests passed.`);
